server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sailun?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 3
      max-active: 30




mybatis:
    mapper-locations: classpath*:mapper/*.xml


